# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d0fd76a7aab8f1c965e29be86ed50e73"
name = "discount-app"
handle = "discount-app-1059"
application_url = "https://plugins-miracle-pollution-joel.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://plugins-miracle-pollution-joel.trycloudflare.com/auth/callback",
  "https://plugins-miracle-pollution-joel.trycloudflare.com/auth/shopify/callback",
  "https://plugins-miracle-pollution-joel.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
